name: redpanda_light_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  pointycastle: ^4.0.0
  collection: ^1.19.1
  equatable: ^2.0.7
  hex: ^0.2.0
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  # path: ^1.9.0

dev_dependencies:
  arch_test: ^0.1.0
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.0
  path: ^1.9.0
